version: "3.9"
services:
  my_nuxt_docker:
    build: .
    volumes:
      - ./nuxt-app:/app
      - app_node_modules:/app/node_modules
      - app_dotnuxt:/app/.nuxt
    command: [yarn, run, dev]
    ports:
      - "8000:3000"

  server:
      build: ./server
      ports:
        - 8081:8081
      volumes:
        - ./server:/data

volumes:
  app_node_modules:
  app_dotnuxt: