name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          docker compose build
          echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
          docker compose push

      - name: Release to Heroku
        run: |
          heroku container:release web --app "$HEROKU_APP_NAME"